In [2]:
import torch
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
import numpy as np
from vit_model import SingleImageTransformer
from dataset import BarLinkageDataset 
import matplotlib.pyplot as plt
torch.set_float32_matmul_precision('medium')

from dataset_generation.curve_plot import get_pca_inclination, rotate_curve
import scipy.spatial.distance as sciDist
from tqdm import tqdm
import requests
import time
import matplotlib.pyplot as plt
import os
import json
import torch.nn.functional as F

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [3]:
# Headless simulator version
index = 0 # local server index 
API_ENDPOINT = f"http://localhost:4000/simulation"
HEADERS = {"Content-Type": "application/json"}
speedscale = 1
steps = 360
minsteps = int(steps*20/360)

In [4]:
checkpoint_path = "weights/transformer_weights_VIT/d1024_h32_n6_bs512_lr5e-05_best.pth"
data_dir = "/home/anurizada/Documents/processed_dataset"
batch_size = 1

dataset = BarLinkageDataset(data_dir=data_dir)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

In [5]:
checkpoint = torch.load(checkpoint_path, map_location=device)
model_config = checkpoint['model_config']

# Initialize model
model = SingleImageTransformer(
    tgt_seq_len=model_config['tgt_seq_len'],
    d_model=model_config['d_model'],
    h=model_config['h'],
    N=model_config['N'],
    num_labels=model_config['num_labels'],
    vocab_size=model_config['vocab_size'],
).to(device)

# Load weights
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

/home/anurizada/anaconda3/envs/transformer/lib/python3.10/site-packages/torch/nn/modules/transformer.py:382: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(


SingleImageTransformer(
  (tgt_embed): InputEmbeddings(
    (embedding): Embedding(221, 1024)
  )
  (decoder_positional_encoding): PositionalEncoding(
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (image_encoder): ViTEncoder(
    (patch_embed): Conv2d(1, 1024, kernel_size=(8, 8), stride=(8, 8), bias=False)
    (encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-5): 6 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=1024, out_features=1024, bias=True)
          )
          (linear1): Linear(in_features=1024, out_features=4096, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=4096, out_features=1024, bias=True)
          (norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.1, inplace=False)
          (dropout

In [7]:
# ===============================
# CONFIG
# ===============================
MAX_SAMPLES = 50
TEMPERATURES = [0.1, 0.2, 0.3, 0.4, 0.5, 0.7, 1.0, 1.3, 1.5, 1.7, 2.0]

SOS_TOKEN, EOS_TOKEN, PAD_TOKEN = 0, 1, 2
NUM_SPECIAL_TOKENS = 3
NUM_MECH_TYPES = 17
BIN_OFFSET = NUM_SPECIAL_TOKENS + NUM_MECH_TYPES  # = 20

# Define externally:
# API_ENDPOINT, HEADERS, speedscale, steps, minsteps

label_mapping_path = "/home/anurizada/Documents/processed_dataset/label_mapping.json"
coupler_mapping_path = "/home/anurizada/Documents/transformer/BSIdict.json"

with open(label_mapping_path, "r") as f:
    label_mapping = json.load(f)
index_to_label = label_mapping["index_to_label"]

with open(coupler_mapping_path, "r") as f:
    coupler_mapping = json.load(f)

def coupler_index_for(mech_type: str) -> int:
    """Return coupler curve index from BSIdict.json."""
    if mech_type in coupler_mapping and "c" in coupler_mapping[mech_type]:
        cvec = coupler_mapping[mech_type]["c"]
        if isinstance(cvec, list) and 1 in cvec:
            return cvec.index(1)
    return -1

# ===============================
# BINNER
# ===============================
class CoordinateBinner:
    def __init__(self, kappa=1.0, num_bins=200):
        self.kappa = kappa
        self.num_bins = num_bins
        self.bin_edges = np.linspace(-kappa, kappa, num_bins + 1)
        self.bin_centers = (self.bin_edges[:-1] + self.bin_edges[1:]) / 2

    def bin_to_value_torch(self, bin_index_tensor):
        bin_index_tensor = torch.clamp(bin_index_tensor, 0, self.num_bins - 1)
        device = bin_index_tensor.device
        bin_centers_tensor = torch.tensor(self.bin_centers, device=device, dtype=torch.float32)
        return bin_centers_tensor[bin_index_tensor]

binner = CoordinateBinner(kappa=1.0, num_bins=201)

# ===============================
# AUTOREGRESSIVE PREDICTION
# ===============================
def predict_autoregressive(model, image, max_seq_len, device, temperature=1.0, top_k=None):
    model.eval()
    with torch.no_grad():
        decoder_input = torch.tensor([[SOS_TOKEN]], device=device, dtype=torch.long)
        for _ in range(max_seq_len):
            T = decoder_input.size(1)
            causal_mask = torch.tril(torch.ones(T, T, device=device)).bool()

            logits = model(decoder_input, causal_mask, image, None)
            next_logits = logits[:, -1, :] / float(temperature)
            probs = F.softmax(next_logits, dim=-1)

            if top_k is None:
                next_token = torch.argmax(probs, dim=-1)
            else:
                k = min(int(top_k), probs.size(-1))
                topk_probs, topk_idx = torch.topk(probs, k=k, dim=-1)
                sampled = torch.multinomial(topk_probs, num_samples=1)
                next_token = topk_idx.gather(-1, sampled).squeeze(1)

            token = int(next_token.item())
            decoder_input = torch.cat([decoder_input, next_token.unsqueeze(1)], dim=1)
            if token == EOS_TOKEN:
                break
    return decoder_input.squeeze(0).cpu().numpy()

# ===============================
# MAIN LOOP
# ===============================
print("Starting multi-temperature coupler curve generation...")
os.makedirs("results_coupler", exist_ok=True)

for i, batch in enumerate(tqdm(dataloader, total=MAX_SAMPLES, desc="Simulating")):
    if i >= MAX_SAMPLES:
        break

    image = batch["images"].to(device)
    gt_tokens = batch["labels_discrete"][0].numpy()

    # --- Ground Truth ---
    gt_mech_idx = gt_tokens[0] - NUM_SPECIAL_TOKENS
    gt_mech_name = index_to_label.get(str(gt_mech_idx), "UNKNOWN")
    gt_coord_tokens = [t for t in gt_tokens[1:] if t >= BIN_OFFSET]
    if len(gt_coord_tokens) < 4:
        continue
    gt_coords_tensor = torch.tensor(gt_coord_tokens) - BIN_OFFSET
    gt_coords_float = binner.bin_to_value_torch(gt_coords_tensor).cpu().numpy()
    if gt_coords_float.size % 2 == 1:
        gt_coords_float = gt_coords_float[:-1]
    gt_points = gt_coords_float.reshape(-1, 2)

    # Create subfolder for this sample
    sample_dir = f"results_coupler/sample_{i:03d}_{gt_mech_name}"
    os.makedirs(sample_dir, exist_ok=True)

    # --- Simulate GT coupler ---
    ex_gt = {
        "params": gt_points.tolist(),
        "type": gt_mech_name,
        "speedScale": speedscale,
        "steps": steps,
        "relativeTolerance": 0.1,
    }
    try:
        temp = requests.post(url=API_ENDPOINT, headers=HEADERS, data=json.dumps([ex_gt])).json()
        P = np.array(temp[0]["poses"]) if isinstance(temp, list) and temp and "poses" in temp[0] else None
    except Exception as e:
        print(f"GT sim failed: {e}")
        continue
    if P is None or P.shape[0] < minsteps:
        continue

    coup_idx_gt = coupler_index_for(gt_mech_name)
    if coup_idx_gt < 0:
        continue
    original_x, original_y = P[:, coup_idx_gt, 0], P[:, coup_idx_gt, 1]
    orig_phi = -get_pca_inclination(original_x, original_y)
    orig_denom = np.sqrt(np.var(original_x) + np.var(original_y)) + 1e-8
    ox_mean, oy_mean = np.mean(original_x), np.mean(original_y)

    print(f"\n=== Sample {i} | GT={gt_mech_name} ===")
    print("GT joint positions:")
    for j, (x, y) in enumerate(gt_points):
        print(f"  J{j}: ({x:.3f}, {y:.3f})")

    # --- Multiple Predictions (different temperatures) ---
    for temp_val in TEMPERATURES:
        pred_tokens = predict_autoregressive(model, image, model_config["tgt_seq_len"], device, temperature=temp_val, top_k=3)
        mech_idx = pred_tokens[1] - NUM_SPECIAL_TOKENS if len(pred_tokens) > 1 else -1
        mech_name = index_to_label.get(str(mech_idx), "UNKNOWN")

        coord_tokens = [t for t in pred_tokens if t >= BIN_OFFSET]
        if len(coord_tokens) < 4:
            continue
        coords_tensor = torch.tensor(coord_tokens) - BIN_OFFSET
        coords_float = binner.bin_to_value_torch(coords_tensor).cpu().numpy()
        if coords_float.size % 2 == 1:
            coords_float = coords_float[:-1]
        pred_points = coords_float.reshape(-1, 2)

        print(f"\n[Temp={temp_val:.1f}] Pred mech: {mech_name}")
        print("Pred joint positions:")
        for j, (x, y) in enumerate(pred_points):
            print(f"  J{j}: ({x:.3f}, {y:.3f})")

        # --- Simulate predicted coupler ---
        ex_pred = {
            "params": pred_points.tolist(),
            "type": mech_name,
            "speedScale": speedscale,
            "steps": steps,
            "relativeTolerance": 0.1,
        }
        try:
            temp = requests.post(url=API_ENDPOINT, headers=HEADERS, data=json.dumps([ex_pred])).json()
            Pp = np.array(temp[0]["poses"]) if isinstance(temp, list) and temp and "poses" in temp[0] else None
        except Exception as e:
            print(f"Pred sim failed (temp={temp_val}): {e}")
            continue
        print(Pp)
        
        if Pp is None:
            continue

        if P.shape[0] < minsteps:
            continue

        coup_idx_pred = coupler_index_for(mech_name)
        if coup_idx_pred < 0:
            continue
        generated_x, generated_y = Pp[:, coup_idx_pred, 0], Pp[:, coup_idx_pred, 1]
        if np.isnan(generated_x).any() or np.isinf(generated_x).any():
            continue

        # --- Align predicted to GT ---
        gen_phi = -get_pca_inclination(generated_x, generated_y)
        rotation = gen_phi - orig_phi
        generated_x, generated_y = rotate_curve(generated_x, generated_y, rotation)
        gen_denom = np.sqrt(np.var(generated_x) + np.var(generated_y)) + 1e-8
        scale = orig_denom / gen_denom
        generated_x *= scale
        generated_y *= scale
        gx_mean, gy_mean = np.mean(generated_x), np.mean(generated_y)
        generated_x -= (gx_mean - ox_mean)
        generated_y -= (gy_mean - oy_mean)

        # --- Plot ---
        plt.figure(figsize=(6, 6))
        plt.plot(original_x, original_y, "r-", label=f"GT Coupler ({gt_mech_name})")
        plt.plot(generated_x, generated_y, "g--", label=f"Pred Coupler ({mech_name})")

        # Plot joint points
        plt.scatter(gt_points[:, 0], gt_points[:, 1], color="red", s=40, zorder=5)
        for j, (x, y) in enumerate(gt_points):
            plt.text(x, y, f"J{j}", color="red", fontsize=9, weight="bold")

        plt.scatter(pred_points[:, 0], pred_points[:, 1], color="green", s=40, zorder=5)
        for j, (x, y) in enumerate(pred_points):
            plt.text(x, y, f"J{j}", color="green", fontsize=9, weight="bold")

        plt.axis("equal")
        plt.legend()
        plt.title(f"Sample {i} | GT={gt_mech_name} | Pred={mech_name} | Temp={temp_val}")
        plt.tight_layout()
        save_path = os.path.join(sample_dir, f"temp_{temp_val:.1f}.png")
        plt.savefig(save_path)
        plt.close()
        print(f"✅ Saved: {save_path}")

print("✅ Finished all temperature variations.")


Starting multi-temperature coupler curve generation...


Simulating:   0%|          | 0/50 [00:00<?, ?it/s]


=== Sample 0 | GT=RRRR ===
GT joint positions:
  J0: (0.478, 0.816)
  J1: (-0.716, -0.219)
  J2: (0.488, 0.070)
  J3: (0.637, 0.199)
  J4: (0.239, -0.557)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (0.478, 0.816)
  J1: (-0.716, -0.219)
  J2: (0.488, 0.070)
  J3: (0.637, 0.199)
  J4: (0.239, -0.557)
[[[ 0.47761193  0.81592041]
  [-1.06840365  0.48971845]
  [ 0.48756218  0.06965174]
  [ 0.30575519  0.14682139]
  [-0.42622189 -0.29418706]]

 [[ 0.47761193  0.81592041]
  [-1.06247517  0.46278644]
  [ 0.48756218  0.06965174]
  [ 0.32594549  0.18318138]
  [-0.38506677 -0.29088663]]

 [[ 0.47761193  0.81592041]
  [-1.05607757  0.43596199]
  [ 0.48756218  0.06965174]
  [ 0.34071373  0.20172924]
  [-0.35447981 -0.29524647]]

 [[ 0.47761193  0.81592041]
  [-1.04921279  0.40925329]
  [ 0.48756218  0.06965174]
  [ 0.35367702  0.21485401]
  [-0.32709617 -0.30169877]]

 [[ 0.47761193  0.81592041]
  [-1.04188293  0.38266846]
  [ 0.48756218  0.06965174]
  [ 0.36560953  0.22501095]
  [-0.

Simulating:   2%|▏         | 1/50 [00:02<02:21,  2.89s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (0.478, -0.716)
  J1: (-0.219, -0.488)
  J2: (0.816, -0.557)
  J3: (0.587, -0.557)
  J4: (0.199, -0.408)
[[[ 4.77611929e-01 -7.16417909e-01]
  [ 6.44891301e-01 -2.60486874e-03]
  [ 8.15920413e-01 -5.57213902e-01]
  [ 8.70888998e-01 -7.79370152e-01]
  [ 8.69989793e-01 -3.63598349e-01]]

 [[ 4.77611929e-01 -7.16417909e-01]
  [ 6.32408068e-01  2.05841660e-04]
  [ 8.15920413e-01 -5.57213902e-01]
  [ 8.23171899e-01 -7.85954718e-01]
  [ 8.41010014e-01 -3.70564778e-01]]

 [[ 4.77611929e-01 -7.16417909e-01]
  [ 6.19877683e-01  2.79826153e-03]
  [ 8.15920413e-01 -5.57213902e-01]
  [ 8.01192275e-01 -7.85595221e-01]
  [ 8.24014615e-01 -3.70449293e-01]]

 [[ 4.77611929e-01 -7.16417909e-01]
  [ 6.07303963e-01  5.17160118e-03]
  [ 8.15920413e-01 -5.57213902e-01]
  [ 7.85205266e-01 -7.83999097e-01]
  [ 8.09823840e-01 -3.68955814e-01]]

 [[ 4.77611929e-01 -7.16417909e-01]
  [ 5.94690736e-01  7.32513768e-03]
  [ 8.15920413e-01 -5.57213902e-01]
  [

Simulating:   4%|▍         | 2/50 [00:06<02:34,  3.21s/it]


[Temp=2.0] Pred mech: Watt2T2A1
Pred joint positions:
  J0: (-0.905, 0.109)
  J1: (0.985, -0.398)
  J2: (-0.468, 0.358)
  J3: (0.458, 0.030)
  J4: (-0.448, -0.816)
  J5: (-0.249, 0.388)
  J6: (-0.458, 0.766)
  J7: (0.209, -0.736)
[[[-0.90547264  0.10945274]
  [ 0.95592516 -0.4962581 ]
  [-0.46766168  0.35820895]
  ...
  [-0.29615729  0.36550808]
  [-0.45771143  0.76616913]
  [ 0.00779958 -0.80979449]]

 [[-0.90547264  0.10945274]
  [ 0.96621278 -0.46367997]
  [-0.46766168  0.35820895]
  ...
  [-0.27605264  0.37421364]
  [-0.45771143  0.76616913]
  [ 0.09977148 -0.78011826]]

 [[-0.90547264  0.10945274]
  [ 0.97593025 -0.43092727]
  [-0.46766168  0.35820895]
  ...
  [-0.26175895  0.3811605 ]
  [-0.45771143  0.76616913]
  [ 0.15879991 -0.75763542]]

 ...

 [[-0.90547264  0.10945274]
  [-0.39800994  2.00000001]
  [-0.46766168  0.35820895]
  ...
  [-0.57985285  1.18054878]
  [-0.45771143  0.76616913]
  [ 0.58666758  1.51663804]]

 [[-0.90547264  0.10945274]
  [-0.43108183  2.00856852]
  [

Simulating:   6%|▌         | 3/50 [00:10<02:42,  3.45s/it]


[Temp=2.0] Pred mech: Steph3T1A2
Pred joint positions:
  J0: (0.100, 0.915)
  J1: (-0.925, 0.706)
  J2: (-0.935, -0.358)
  J3: (-0.796, -0.557)
  J4: (0.030, 0.697)
  J5: (-0.587, 0.219)
  J6: (-0.697, 0.985)
[[[ 0.09950249  0.91542286]
  [-0.33464402  1.8670263 ]
  [-0.93532336 -0.35820895]
  ...
  [-0.5732533   0.94203047]
  [-0.92495156  0.24560664]
  [-0.69651741  0.98507464]]

 [[ 0.09950249  0.91542286]
  [-0.35118567  1.85930447]
  [-0.93532336 -0.35820895]
  ...
  [-0.52147336  0.91932905]
  [-0.90437445  0.23956104]
  [-0.69651741  0.98507464]]

 [[ 0.09950249  0.91542286]
  [-0.36759004  1.85129512]
  [-0.93532336 -0.35820895]
  ...
  [-0.48658533  0.90345965]
  [-0.8901172   0.23573218]
  [-0.69651741  0.98507464]]

 ...

 [[ 0.09950249  0.91542286]
  [-0.17960089 -0.09261167]
  [-0.93532336 -0.35820895]
  ...
  [ 0.45604186  0.62048719]
  [-0.27135465  0.33836627]
  [-0.69651741  0.98507464]]

 [[ 0.09950249  0.91542286]
  [-0.16196575 -0.09732917]
  [-0.93532336 -0.358208

Simulating:   8%|▊         | 4/50 [00:13<02:33,  3.34s/it]


[Temp=2.0] Pred mech: Steph3T1A1
Pred joint positions:
  J0: (0.408, 0.199)
  J1: (-0.119, 0.736)
  J2: (0.478, 0.697)
  J3: (0.975, 0.000)
  J4: (-0.119, 0.796)
  J5: (0.408, 0.000)
  J6: (-0.627, 0.010)
[[[ 0.40796021  0.19900498]
  [ 0.03763343  0.85450154]
  [ 0.47761193  0.69651741]
  ...
  [ 0.0293938   0.91363171]
  [ 0.40765734  0.03688983]
  [-0.62686568  0.00995025]]

 [[ 0.40796021  0.19900498]
  [ 0.02624984  0.84793861]
  [ 0.47761193  0.69651741]
  ...
  [ 0.0213887   0.90744187]
  [ 0.40772327  0.03422641]
  [-0.62686568  0.00995025]]

 [[ 0.40796021  0.19900498]
  [ 0.01498252  0.84117801]
  [ 0.47761193  0.69651741]
  ...
  [ 0.0119972   0.90080482]
  [ 0.40777673  0.03182945]
  [-0.62686568  0.00995025]]

 ...

 [[ 0.40796021  0.19900498]
  [ 0.96335103  0.70729494]
  [ 0.47761193  0.69651741]
  ...
  [ 0.98490453  0.65161985]
  [ 0.40166879 -0.10441964]
  [-0.62686568  0.00995025]]

 [[ 0.40796021  0.19900498]
  [ 0.95439556  0.71691043]
  [ 0.47761193  0.69651741]


Simulating:  10%|█         | 5/50 [00:16<02:31,  3.36s/it]


[Temp=2.0] Pred mech: Watt2T2A1
Pred joint positions:
  J0: (0.866, 0.348)
  J1: (0.746, -0.687)
  J2: (0.587, -0.080)
  J3: (-0.219, -0.995)
  J4: (-0.786, -0.607)
  J5: (-0.766, -0.189)
  J6: (-0.368, -0.428)
  J7: (0.149, -0.647)
[[[ 0.86567163  0.3482587 ]
  [ 0.38335089 -0.57504428]
  [ 0.58706468 -0.07960199]
  [-0.60341523 -0.34482739]
  [-0.83327832  0.30280556]
  [-0.5419261   0.00254057]
  [-0.3681592  -0.42786071]
  [-1.50184235 -0.35250814]]

 [[ 0.86567163  0.3482587 ]
  [ 0.39953821 -0.58332132]
  [ 0.58706468 -0.07960199]
  [-0.59396316 -0.38416754]
  [-0.8451806   0.25548493]
  [-0.50163852  0.01668791]
  [-0.3681592  -0.42786071]
  [-1.37561619 -0.5159112 ]]

 [[ 0.86567163  0.3482587 ]
  [ 0.41586752 -0.59131458]
  [ 0.58706468 -0.07960199]
  [-0.58329941 -0.42287277]
  [-0.85543312  0.20816505]
  [-0.48050494  0.02249319]
  [-0.3681592  -0.42786071]
  [-1.26664313 -0.63285828]]

 [[ 0.86567163  0.3482587 ]
  [ 0.43233384 -0.59902165]
  [ 0.58706468 -0.07960199]
  [-

Simulating:  12%|█▏        | 6/50 [00:19<02:27,  3.35s/it]


[Temp=2.0] Pred mech: Watt1T1A1
Pred joint positions:
  J0: (-0.030, -0.338)
  J1: (0.786, -0.060)
  J2: (-0.657, 0.129)
  J3: (0.547, -0.796)
  J4: (0.746, 0.905)
  J5: (-0.846, 0.886)
  J6: (0.368, 0.050)
  J7: (-0.308, 0.786)
[[[-2.98507456e-02 -3.38308454e-01]
  [-7.37369265e-01 -8.31020790e-01]
  [-6.56716406e-01  1.29353240e-01]
  ...
  [ 7.10214056e-02  4.08649471e-01]
  [-5.86113387e-01 -9.10591710e-01]
  [-1.13834838e+00 -7.69180821e-02]]

 [[-2.98507456e-02 -3.38308454e-01]
  [-7.28662490e-01 -8.43293648e-01]
  [-6.56716406e-01  1.29353240e-01]
  ...
  [ 7.02168905e-02  4.10736768e-01]
  [-6.38449487e-01 -8.81553987e-01]
  [-1.11033981e+00  8.92101933e-05]]

 [[-2.98507456e-02 -3.38308454e-01]
  [-7.19742851e-01 -8.55412683e-01]
  [-6.56716406e-01  1.29353240e-01]
  ...
  [ 6.92720859e-02  4.13165532e-01]
  [-6.66128046e-01 -8.64101110e-01]
  [-1.08033009e+00  4.60702346e-02]]

 ...

 [[-2.98507456e-02 -3.38308454e-01]
  [ 2.67106310e-01  4.71113815e-01]
  [-6.56716406e-01  

Simulating:  14%|█▍        | 7/50 [00:22<02:17,  3.21s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.388, -0.249)
  J1: (-0.716, -0.458)
  J2: (-0.507, 0.119)
  J3: (0.786, -0.836)
  J4: (-0.348, -0.338)
[[[-0.38805971 -0.24875621]
  [-0.56760148  0.09656413]
  [-0.50746268  0.11940298]
  [-1.65372122 -1.00832478]
  [-0.65080824 -0.28142384]]

 [[-0.38805971 -0.24875621]
  [-0.5736008   0.0933781 ]
  [-0.50746268  0.11940298]
  [-1.42700663 -1.19973214]
  [-0.58257571 -0.29355564]]

 [[-0.38805971 -0.24875621]
  [-0.57954361  0.09008786]
  [-0.50746268  0.11940298]
  [-1.25553678 -1.30399566]
  [-0.53757043 -0.29466729]]

 ...

 [[-0.38805971 -0.24875621]
  [-0.43192465  0.13797012]
  [-0.50746268  0.11940298]
  [ 0.43926501  1.4191665 ]
  [-0.41760482  0.52474294]]

 [[-0.38805971 -0.24875621]
  [-0.43866727  0.13714567]
  [-0.50746268  0.11940298]
  [ 0.56701972  1.31571653]
  [-0.38226228  0.52005133]]

 [[-0.38805971 -0.24875621]
  [-0.44539448  0.13620367]
  [-0.50746268  0.11940298]
  [ 0.74518693  1.12764278]
  [-0.325

Simulating:  16%|█▌        | 8/50 [00:26<02:16,  3.26s/it]


[Temp=2.0] Pred mech: Watt1T2A1
Pred joint positions:
  J0: (0.458, -0.269)
  J1: (0.229, -0.418)
  J2: (-0.159, -0.090)
  J3: (0.637, 0.308)
  J4: (-0.179, 0.338)
  J5: (0.836, -0.428)
  J6: (0.040, 0.129)
  J7: (-0.129, -0.557)
[[[ 0.45771143 -0.26865673]
  [ 0.22628573 -0.41389364]
  [-0.15920398 -0.08955224]
  ...
  [ 0.83733632 -0.42337044]
  [ 0.05819026  0.15720385]
  [-0.13124924 -0.5240452 ]]

 [[ 0.45771143 -0.26865673]
  [ 0.22885571 -0.41791046]
  [-0.15920398 -0.08955224]
  ...
  [ 0.83582091 -0.42786071]
  [ 0.03980099  0.12935324]
  [-0.12935324 -0.5572139 ]]

 [[ 0.45771143 -0.26865673]
  [ 0.23149541 -0.42188181]
  [-0.15920398 -0.08955224]
  ...
  [ 0.83434505 -0.43217081]
  [ 0.03095778  0.11436738]
  [-0.12901636 -0.57439663]]

 ...

 [[ 0.45771143 -0.26865673]
  [ 0.35046558 -0.01736021]
  [-0.15920398 -0.08955224]
  ...
  [ 0.75659372  0.42604618]
  [-0.18402694  0.18239095]
  [ 0.22833154 -0.39202012]]

 [[ 0.45771143 -0.26865673]
  [ 0.34609618 -0.01927018]
  [

Simulating:  18%|█▊        | 9/50 [00:29<02:19,  3.39s/it]

✅ Saved: results_coupler/sample_008_Watt1T2A1/temp_2.0.png

=== Sample 9 | GT=RRRR ===
GT joint positions:
  J0: (0.199, 0.965)
  J1: (0.318, 0.070)
  J2: (-0.716, -0.100)
  J3: (0.169, -0.806)
  J4: (0.129, 0.279)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (0.199, 0.965)
  J1: (0.318, 0.070)
  J2: (-0.716, -0.100)
  J3: (0.169, -0.806)
  J4: (0.129, 0.279)
[[[ 0.19900498  0.96517414]
  [-0.08907796  1.82146011]
  [-0.71641791 -0.09950249]
  [-0.34862736  0.9719753 ]
  [-0.24998278  2.05279018]]

 [[ 0.19900498  0.96517414]
  [-0.10397833  1.81630195]
  [-0.71641791 -0.09950249]
  [-0.27890338  0.94544516]
  [-0.28680987  2.03072349]]

 [[ 0.19900498  0.96517414]
  [-0.11878641  1.81088453]
  [-0.71641791 -0.09950249]
  [-0.24839047  0.93213933]
  [-0.31247389  2.01555287]]

 ...

 [[ 0.19900498  0.96517414]
  [ 1.08135899  0.77108953]
  [-0.71641791 -0.09950249]
  [ 0.3604658   0.25214509]
  [ 1.09335717  1.05262108]]

 [[ 0.19900498  0.96517414]
  [ 1.08461185  0.7865182

Simulating:  20%|██        | 10/50 [00:32<02:04,  3.11s/it]

✅ Saved: results_coupler/sample_009_RRRR/temp_1.7.png

[Temp=2.0] Pred mech: UNKNOWN
Pred joint positions:
  J0: (-0.806, 0.119)
  J1: (0.965, -0.408)
  J2: (-0.299, 0.677)
  J3: (0.159, -0.836)
  J4: (-0.806, 0.856)
  J5: (0.438, -0.716)
  J6: (-0.756, 0.378)
  J7: (0.438, 0.070)
None

=== Sample 10 | GT=Watt2T1A2 ===
GT joint positions:
  J0: (-0.547, 0.687)
  J1: (-0.896, -0.766)
  J2: (0.896, 0.388)
  J3: (-0.010, 0.776)
  J4: (-0.537, -0.498)
  J5: (0.388, 0.527)
  J6: (0.816, -0.189)
  J7: (-0.617, -0.010)

[Temp=0.1] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (-0.547, 0.687)
  J1: (-0.896, -0.766)
  J2: (0.896, 0.388)
  J3: (-0.010, 0.776)
  J4: (-0.537, -0.498)
  J5: (0.388, 0.527)
  J6: (0.816, -0.189)
  J7: (-0.617, -0.010)
[[[-0.54726368  0.68656719]
  [-1.8207595  -0.0944164 ]
  [ 0.89552242  0.38805971]
  ...
  [-0.00280134 -0.02776586]
  [ 0.81592041 -0.18905473]
  [-1.07468957  0.21032699]]

 [[-0.54726368  0.68656719]
  [-1.80693549 -0.11652302]
  [ 0.89552242  0.

Simulating:  22%|██▏       | 11/50 [00:35<02:03,  3.17s/it]


[Temp=2.0] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (-0.547, 0.687)
  J1: (-0.896, -0.766)
  J2: (0.896, 0.388)
  J3: (-0.010, 0.776)
  J4: (-0.537, -0.498)
  J5: (0.388, -0.010)
  J6: (-0.060, 0.338)
  J7: (-0.129, 0.527)
[[[-0.54726368  0.68656719]
  [-1.8207595  -0.0944164 ]
  [ 0.89552242  0.38805971]
  ...
  [-0.33154011 -0.159565  ]
  [-0.05970149  0.33830845]
  [-0.34914519  0.21314232]]

 [[-0.54726368  0.68656719]
  [-1.80693549 -0.11652302]
  [ 0.89552242  0.38805971]
  ...
  [-0.31668748 -0.16739147]
  [-0.05970149  0.33830845]
  [-0.34916497  0.25109925]]

 [[-0.54726368  0.68656719]
  [-1.79272778 -0.13838501]
  [ 0.89552242  0.38805971]
  ...
  [-0.30162938 -0.17476572]
  [-0.05970149  0.33830845]
  [-0.34718717  0.27471713]]

 ...

 [[-0.54726368  0.68656719]
  [ 0.50017757 -0.37860593]
  [ 0.89552242  0.38805971]
  ...
  [-0.18090252  0.89246053]
  [-0.05970149  0.33830845]
  [ 0.79234755  1.09614075]]

 [[-0.54726368  0.68656719]
  [ 0.51860788 -0.36016333]
  

Simulating:  24%|██▍       | 12/50 [00:38<01:59,  3.15s/it]


[Temp=2.0] Pred mech: Watt1T3A1
Pred joint positions:
  J0: (-0.866, -0.756)
  J1: (-0.428, 0.657)
  J2: (0.289, 0.925)
  J3: (-0.468, -0.677)
  J4: (-0.507, -0.040)
  J5: (0.836, -0.418)
  J6: (0.348, 0.896)
[[[-8.65671635e-01 -7.56218910e-01]
  [-2.92836948e-01 -2.12000960e+00]
  [ 2.88557202e-01  9.25373137e-01]
  ...
  [-6.01420862e-02 -1.45870327e+00]
  [ 1.21046657e+00 -1.94444479e-01]
  [-1.90537391e-01 -1.97717131e-01]]

 [[-8.65671635e-01 -7.56218910e-01]
  [-2.69122764e-01 -2.10980454e+00]
  [ 2.88557202e-01  9.25373137e-01]
  ...
  [ 5.02946836e-04 -1.46267632e+00]
  [ 1.27013850e+00 -1.42525052e-01]
  [-1.29620634e-01 -2.01662114e-01]]

 [[-8.65671635e-01 -7.56218910e-01]
  [-2.45590295e-01 -2.09918717e+00]
  [ 2.88557202e-01  9.25373137e-01]
  ...
  [ 4.65187754e-02 -1.46189191e+00]
  [ 1.31032754e+00 -1.04138276e-01]
  [-8.73094336e-02 -2.01265483e-01]]

 ...

 [[-8.65671635e-01 -7.56218910e-01]
  [-2.34087954e+00 -6.47470337e-01]
  [ 2.88557202e-01  9.25373137e-01]
  ..

Simulating:  26%|██▌       | 13/50 [00:42<02:01,  3.29s/it]

✅ Saved: results_coupler/sample_012_Steph1T2/temp_2.0.png

=== Sample 13 | GT=Watt2T2A1 ===
GT joint positions:
  J0: (0.627, 0.517)
  J1: (-0.040, 0.040)
  J2: (0.577, -0.995)
  J3: (0.080, 0.856)
  J4: (-0.786, -0.726)
  J5: (-0.348, 0.736)
  J6: (0.726, 0.119)
  J7: (0.249, -0.657)

[Temp=0.1] Pred mech: Watt2T2A1
Pred joint positions:
  J0: (0.627, 0.517)
  J1: (-0.040, 0.040)
  J2: (0.577, -0.995)
  J3: (0.080, 0.856)
  J4: (-0.786, -0.726)
  J5: (-0.348, 0.736)
  J6: (0.726, 0.119)
  J7: (0.249, -0.657)
[[[ 0.62686568  0.51741296]
  [ 1.18216383 -0.08607823]
  [ 0.5771144  -0.99502486]
  ...
  [ 0.91163523  1.3445902 ]
  [ 0.72636819  0.11940298]
  [ 0.85270641 -0.16984045]]

 [[ 0.62686568  0.51741296]
  [ 1.19261163 -0.07629503]
  [ 0.5771144  -0.99502486]
  ...
  [ 1.15973355  1.28026562]
  [ 0.72636819  0.11940298]
  [ 0.92500122 -0.21702311]]

 [[ 0.62686568  0.51741296]
  [ 1.2028871  -0.06633097]
  [ 0.5771144  -0.99502486]
  ...
  [ 1.27817433  1.22887023]
  [ 0.72636819 

Simulating:  28%|██▊       | 14/50 [00:45<01:58,  3.30s/it]

✅ Saved: results_coupler/sample_013_Watt2T2A1/temp_2.0.png

=== Sample 14 | GT=Steph1T2 ===
GT joint positions:
  J0: (-0.697, -0.955)
  J1: (0.060, -0.995)
  J2: (-0.527, 0.945)
  J3: (-0.030, 0.935)
  J4: (0.965, -0.547)
  J5: (0.418, 0.040)
  J6: (-0.617, 0.378)
  J7: (0.776, 0.965)

[Temp=0.1] Pred mech: Steph1T2
Pred joint positions:
  J0: (-0.697, -0.955)
  J1: (0.060, -0.995)
  J2: (-0.527, 0.945)
  J3: (-0.030, 0.935)
  J4: (0.965, -0.547)
  J5: (0.418, 0.040)
  J6: (-0.617, 0.378)
  J7: (0.776, 0.965)
[[[-6.96517408e-01 -9.55223858e-01]
  [-1.16526982e-01 -1.44211425e+00]
  [-5.27363181e-01  9.45273638e-01]
  [-3.67964697e-01  4.73882341e-01]
  [ 8.76085031e-01 -1.62944331e+00]
  [-1.05851072e+00 -2.51098065e-01]
  [-9.32547888e-01 -1.33250943e+00]
  [-2.04885225e+00 -3.13168707e-01]]

 [[-6.96517408e-01 -9.55223858e-01]
  [-1.08117909e-01 -1.43191786e+00]
  [-5.27363181e-01  9.45273638e-01]
  [-3.32393852e-01  4.87447697e-01]
  [ 8.87612268e-01 -1.60189493e+00]
  [-9.65495075

Simulating:  30%|███       | 15/50 [00:49<01:56,  3.32s/it]

✅ Saved: results_coupler/sample_014_Steph1T2/temp_2.0.png

=== Sample 15 | GT=Watt1T2A2 ===
GT joint positions:
  J0: (-0.756, -0.299)
  J1: (0.428, -0.119)
  J2: (0.358, -0.468)
  J3: (0.726, -0.527)
  J4: (-0.020, -0.527)
  J5: (-0.746, 0.149)
  J6: (-0.766, -0.667)
  J7: (-0.289, 0.657)

[Temp=0.1] Pred mech: Watt1T2A2
Pred joint positions:
  J0: (-0.756, -0.299)
  J1: (0.428, -0.119)
  J2: (0.358, -0.468)
  J3: (0.726, -0.527)
  J4: (-0.020, -0.527)
  J5: (-0.746, 0.149)
  J6: (-0.766, -0.667)
  J7: (-0.289, 0.657)
[[[-0.75621891 -0.29850745]
  [ 0.44028057 -0.34862668]
  [ 0.35820895 -0.46766168]
  [ 0.31322912 -0.83790796]
  [-0.15894218 -0.26000553]
  [-0.66101458  0.13912849]
  [-0.80109809 -0.66492298]
  [-0.13343052  0.57349375]]

 [[-0.75621891 -0.29850745]
  [ 0.44097304 -0.32773725]
  [ 0.35820895 -0.46766168]
  [ 0.432419   -0.83317277]
  [-0.16229918 -0.38236546]
  [-0.66866688  0.14072338]
  [-0.87291727 -0.64946896]
  [-0.10788034  0.5312827 ]]

 [[-0.75621891 -0.29850

Simulating:  32%|███▏      | 16/50 [00:52<01:52,  3.32s/it]

✅ Saved: results_coupler/sample_015_Watt1T2A2/temp_2.0.png

=== Sample 16 | GT=Watt1T1A2 ===
GT joint positions:
  J0: (-0.925, -0.816)
  J1: (-0.169, 0.448)
  J2: (0.955, 0.677)
  J3: (0.080, -0.517)
  J4: (-0.935, -0.269)
  J5: (-0.408, -0.159)
  J6: (-0.667, 0.328)
  J7: (0.925, -0.517)

[Temp=0.1] Pred mech: Watt1T1A2
Pred joint positions:
  J0: (-0.925, -0.816)
  J1: (-0.169, 0.448)
  J2: (0.955, 0.677)
  J3: (0.080, -0.517)
  J4: (-0.935, -0.269)
  J5: (-0.408, -0.159)
  J6: (-0.667, 0.328)
  J7: (0.925, -0.517)
[[[-0.92537314 -0.81592041]
  [ 0.51456515 -0.50715512]
  [ 0.95522386  0.67661691]
  ...
  [-0.09220637 -0.74645274]
  [ 0.27019313 -1.16276095]
  [ 1.3211892   0.3019325 ]]

 [[-0.92537314 -0.81592041]
  [ 0.50895714 -0.48207176]
  [ 0.95522386  0.67661691]
  ...
  [-0.09354564 -0.73192256]
  [ 0.20649376 -1.195196  ]
  [ 1.12919068  0.3535293 ]]

 [[-0.92537314 -0.81592041]
  [ 0.50291223 -0.45709009]
  [ 0.95522386  0.67661691]
  ...
  [-0.0951383  -0.71741796]
  [ 0.

Simulating:  34%|███▍      | 17/50 [00:56<01:52,  3.41s/it]

✅ Saved: results_coupler/sample_016_Watt1T1A2/temp_2.0.png

=== Sample 17 | GT=Steph3T1A2 ===
GT joint positions:
  J0: (0.030, 0.328)
  J1: (-0.308, -0.706)
  J2: (0.577, 0.289)
  J3: (-0.010, -0.985)
  J4: (0.169, 0.816)
  J5: (-0.726, -0.687)
  J6: (-0.328, 0.418)

[Temp=0.1] Pred mech: Steph3T1A2
Pred joint positions:
  J0: (0.030, 0.328)
  J1: (-0.308, -0.706)
  J2: (0.577, 0.289)
  J3: (-0.010, -0.985)
  J4: (0.169, 0.816)
  J5: (-0.726, -0.687)
  J6: (-0.328, 0.418)
[[[ 0.02985075  0.3283582 ]
  [ 0.86512676  1.02666417]
  [ 0.5771144   0.2885572 ]
  ...
  [-0.56037053  1.74341809]
  [-1.49211179  0.26311827]
  [-0.3283582   0.41791046]]

 [[ 0.02985075  0.3283582 ]
  [ 0.87718666  1.01198023]
  [ 0.5771144   0.2885572 ]
  ...
  [-0.57268545  1.67805044]
  [-1.47834267  0.18165004]
  [-0.3283582   0.41791046]]

 [[ 0.02985075  0.3283582 ]
  [ 0.88898845  0.99708806]
  [ 0.5771144   0.2885572 ]
  ...
  [-0.5747249   1.63216436]
  [-1.46574842  0.12700441]
  [-0.3283582   0.417910

Simulating:  36%|███▌      | 18/50 [00:59<01:50,  3.44s/it]


[Temp=2.0] Pred mech: Steph3T1A2
Pred joint positions:
  J0: (0.030, 0.328)
  J1: (-0.308, -0.706)
  J2: (0.328, 0.418)
  J3: (0.577, 0.289)
  J4: (0.756, 0.030)
  J5: (0.945, 0.030)
  J6: (0.159, 0.328)
[[[ 0.02985075  0.3283582 ]
  [-0.32646638 -0.70040578]
  [ 0.3283582   0.41791046]
  ...
  [ 0.75400021  0.01254101]
  [ 0.94274935  0.02328652]
  [ 0.15920398  0.3283582 ]]

 [[ 0.02985075  0.3283582 ]
  [-0.3084577  -0.70646769]
  [ 0.3283582   0.41791046]
  ...
  [ 0.75621891  0.02985075]
  [ 0.94527364  0.02985075]
  [ 0.15920398  0.3283582 ]]

 [[ 0.02985075  0.3283582 ]
  [-0.29034597 -0.71221438]
  [ 0.3283582   0.41791046]
  ...
  [ 0.76042929  0.04380975]
  [ 0.94946505  0.04113072]
  [ 0.15920398  0.3283582 ]]

 ...

 [[ 0.02985075  0.3283582 ]
  [ 0.96205127 -0.2340646 ]
  [ 0.3283582   0.41791046]
  ...
  [ 0.46610778  0.96165325]
  [ 0.39305733  1.13602447]
  [ 0.15920398  0.3283582 ]]

 [[ 0.02985075  0.3283582 ]
  [ 0.97172493 -0.21770979]
  [ 0.3283582   0.41791046]
 

Simulating:  38%|███▊      | 19/50 [01:02<01:39,  3.21s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.418, -0.398)
  J1: (0.050, -0.388)
  J2: (-0.587, -0.129)
  J3: (-0.070, 0.925)
  J4: (-0.597, -0.975)
[[[-0.41791046 -0.39800996]
  [ 0.04975124 -0.38805971]
  [-0.58706468 -0.12935324]
  [-0.06965174  0.92537314]
  [-0.5970149  -0.97512436]]

 [[-0.41791046 -0.39800996]
  [ 0.04950636 -0.3798994 ]
  [-0.58706468 -0.12935324]
  [-0.08379723  0.93219551]
  [-0.59100739 -0.97377943]]

 [[-0.41791046 -0.39800996]
  [ 0.0491191  -0.37174461]
  [-0.58706468 -0.12935324]
  [-0.09810507  0.93886134]
  [-0.58505443 -0.97239034]]

 ...

 [[-0.41791046 -0.39800996]
  [ 0.04963109 -0.41254886]
  [-0.58706468 -0.12935324]
  [-0.02819044  0.9040022 ]
  [-0.61537077 -0.97887376]]

 [[-0.41791046 -0.39800996]
  [ 0.04981362 -0.40438692]
  [-0.58706468 -0.12935324]
  [-0.04184827  0.91127299]
  [-0.60919608 -0.97767357]]

 [[-0.41791046 -0.39800996]
  [ 0.04985367 -0.39622304]
  [-0.58706468 -0.12935324]
  [-0.05566872  0.91839779]
  [-0.603

Simulating:  40%|████      | 20/50 [01:05<01:36,  3.22s/it]


[Temp=2.0] Pred mech: Steph1T3
Pred joint positions:
  J0: (-0.199, -0.030)
  J1: (-0.776, -0.746)
  J2: (0.687, -0.109)
  J3: (-0.766, 0.547)
  J4: (0.985, -0.647)
  J5: (0.915, -0.418)
  J6: (0.527, -0.816)
  J7: (0.408, -0.010)
[[[-0.19900498 -0.02985075]
  [-1.11525025 -0.11237504]
  [ 0.68656719 -0.10945274]
  ...
  [ 0.79717257 -0.47726727]
  [ 0.41948218 -0.88513025]
  [ 0.27846011 -0.07017615]]

 [[-0.19900498 -0.02985075]
  [-1.11367045 -0.12835316]
  [ 0.68656719 -0.10945274]
  ...
  [ 0.80025412 -0.47632651]
  [ 0.39242087 -0.854049  ]
  [ 0.27956383 -0.07260787]]

 [[-0.19900498 -0.02985075]
  [-1.11181204 -0.14430127]
  [ 0.68656719 -0.10945274]
  ...
  [ 0.80331149 -0.47536509]
  [ 0.37772251 -0.83296299]
  [ 0.28080908 -0.07490597]]

 ...

 [[-0.19900498 -0.02985075]
  [ 0.14779759 -0.88193268]
  [ 0.68656719 -0.10945274]
  ...
  [ 1.02498489 -0.29109674]
  [ 1.10779301  0.25858049]
  [ 0.2211462   0.51048582]]

 [[-0.19900498 -0.02985075]
  [ 0.16261565 -0.87575037]
  

Simulating:  42%|████▏     | 21/50 [01:08<01:28,  3.06s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.468, 0.428)
  J1: (-0.776, -0.587)
  J2: (-0.577, -0.478)
  J3: (0.139, 0.587)
  J4: (-0.478, 0.408)
[[[-0.46766168  0.42786071]
  [-0.42888681 -0.63219412]
  [-0.5771144  -0.47761193]
  [-1.70384461  0.13661108]
  [-1.45241831 -0.45453005]]

 [[-0.46766168  0.42786071]
  [-0.41039221 -0.63135595]
  [-0.5771144  -0.47761193]
  [-1.81298054 -0.13203162]
  [-1.44879949 -0.66121513]]

 [[-0.46766168  0.42786071]
  [-0.39191505 -0.63019514]
  [-0.5771144  -0.47761193]
  [-1.85391555 -0.34888862]
  [-1.41384298 -0.81686208]]

 ...

 [[-0.46766168  0.42786071]
  [-0.79378532 -0.58152678]
  [-0.5771144  -0.47761193]
  [ 0.07421147  0.6280849 ]
  [-0.53509175  0.424584  ]]

 [[-0.46766168  0.42786071]
  [-0.77611941 -0.58706468]
  [-0.5771144  -0.47761193]
  [ 0.13930348  0.58706468]
  [-0.47761193  0.40796021]]

 [[-0.46766168  0.42786071]
  [-0.75835954 -0.59229344]
  [-0.5771144  -0.47761193]
  [ 0.24368432  0.50883641]
  [-0.38506

Simulating:  44%|████▍     | 22/50 [01:11<01:25,  3.05s/it]

✅ Saved: results_coupler/sample_021_RRRR/temp_1.7.png

[Temp=2.0] Pred mech: UNKNOWN
Pred joint positions:
  J0: (0.716, 0.348)
  J1: (0.965, 0.667)
  J2: (-0.269, -0.020)
  J3: (0.826, -0.876)
  J4: (-0.507, -0.607)
  J5: (0.040, 0.050)
  J6: (0.716, 0.896)
  J7: (0.318, 0.219)
None

=== Sample 22 | GT=Watt2T1A1 ===
GT joint positions:
  J0: (0.478, 0.249)
  J1: (-0.866, -0.428)
  J2: (0.736, 0.736)
  J3: (-0.995, 0.328)
  J4: (0.020, 0.179)
  J5: (-0.109, -0.547)
  J6: (-0.030, 0.935)
  J7: (-0.060, -0.965)

[Temp=0.1] Pred mech: Watt2T1A1
Pred joint positions:
  J0: (0.478, 0.249)
  J1: (-0.866, -0.428)
  J2: (0.736, 0.736)
  J3: (-0.995, 0.328)
  J4: (0.020, 0.179)
  J5: (-0.109, -0.547)
  J6: (-0.030, 0.935)
  J7: (-0.060, -0.965)
[[[ 0.47761193  0.24875621]
  [-0.87727564 -0.40431412]
  [ 0.73631841  0.73631841]
  ...
  [ 0.02521421 -0.54837764]
  [-0.02985075  0.93532336]
  [-0.07559297 -0.94800383]]

 [[ 0.47761193  0.24875621]
  [-0.86567163 -0.42786071]
  [ 0.73631841  0.7363

Simulating:  46%|████▌     | 23/50 [01:14<01:22,  3.06s/it]


[Temp=2.0] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (0.478, 0.249)
  J1: (-0.866, -0.428)
  J2: (0.736, 0.736)
  J3: (-0.995, 0.328)
  J4: (0.020, 0.179)
  J5: (-0.109, -0.547)
  J6: (-0.030, 0.935)
  J7: (-0.060, -0.965)
[[[ 0.47761193  0.24875621]
  [-0.87727564 -0.40431412]
  [ 0.73631841  0.73631841]
  ...
  [-0.02504807 -0.54939134]
  [-0.02985075  0.93532336]
  [-0.07559297 -0.94800383]]

 [[ 0.47761193  0.24875621]
  [-0.86567163 -0.42786071]
  [ 0.73631841  0.73631841]
  ...
  [-0.10945274 -0.54726368]
  [-0.02985075  0.93532336]
  [-0.05970149 -0.96517414]]

 [[ 0.47761193  0.24875621]
  [-0.85365845 -0.45120119]
  [ 0.73631841  0.73631841]
  ...
  [-0.16235664 -0.54347446]
  [-0.02985075  0.93532336]
  [-0.04339126 -0.98201252]]

 ...

 [[ 0.47761193  0.24875621]
  [ 1.667111    1.16925237]
  [ 0.73631841  0.73631841]
  ...
  [ 0.76560481 -0.3183318 ]
  [-0.02985075  0.93532336]
  [ 1.13334817  0.36092641]]

 [[ 0.47761193  0.24875621]
  [ 1.65086496  1.18987179]
  [

Simulating:  48%|████▊     | 24/50 [01:16<01:14,  2.87s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.169, -0.537)
  J1: (0.468, -0.886)
  J2: (0.458, 0.458)
  J3: (0.547, 0.756)
  J4: (-0.159, -0.090)
[[[-0.16915423 -0.53731346]
  [-0.75130444 -0.10381637]
  [ 0.45771143  0.45771143]
  [ 0.75084361  0.56354076]
  [-0.32230428  0.81409816]]

 [[-0.16915423 -0.53731346]
  [-0.75878135 -0.11404232]
  [ 0.45771143  0.45771143]
  [ 0.76675028  0.49797694]
  [-0.29652487  0.78758243]]

 [[-0.16915423 -0.53731346]
  [-0.76607864 -0.1243972 ]
  [ 0.45771143  0.45771143]
  [ 0.76932695  0.46241109]
  [-0.28903368  0.76949113]]

 ...

 [[-0.16915423 -0.53731346]
  [ 0.46148674 -0.89663306]
  [ 0.45771143  0.45771143]
  [ 0.58430779  0.74249149]
  [-0.14419332 -0.08437701]]

 [[-0.16915423 -0.53731346]
  [ 0.46766168 -0.88557214]
  [ 0.45771143  0.45771143]
  [ 0.54726368  0.75621891]
  [-0.15920398 -0.08955224]]

 [[-0.16915423 -0.53731346]
  [ 0.47364264 -0.87440512]
  [ 0.45771143  0.45771143]
  [ 0.46447577  0.76928897]
  [-0.195291

Simulating:  50%|█████     | 25/50 [01:19<01:13,  2.92s/it]


[Temp=2.0] Pred mech: Watt1T2A1
Pred joint positions:
  J0: (0.667, -0.836)
  J1: (-0.060, 0.736)
  J2: (-0.687, 0.886)
  J3: (-0.388, 0.318)
  J4: (-0.945, -0.935)
  J5: (0.836, 0.279)
  J6: (0.846, 0.866)
  J7: (0.080, -0.866)
[[[ 0.66666669 -0.83582091]
  [ 0.46166727  0.88383255]
  [-0.68656719  0.88557214]
  [-0.05675432  0.76675427]
  [-1.28005845  0.14558073]
  [ 0.73533553  1.70059664]
  [ 0.32143032  2.11704162]
  [ 1.02837262  0.36068253]]

 [[ 0.66666669 -0.83582091]
  [ 0.4316864   0.8799929 ]
  [-0.68656719  0.88557214]
  [-0.0709437   0.70727563]
  [-1.21950709 -0.04314538]
  [ 0.80653381  1.56138401]
  [ 0.36170164  1.94461801]
  [ 1.20218108  0.24810423]]

 [[ 0.66666669 -0.83582091]
  [ 0.40177711  0.8756306 ]
  [-0.68656719  0.88557214]
  [-0.08543123  0.6632717 ]
  [-1.17030583 -0.17659536]
  [ 0.8514507   1.45176402]
  [ 0.39630643  1.82269211]
  [ 1.28285784  0.14979304]]

 [[ 0.66666669 -0.83582091]
  [ 0.3719485   0.87074698]
  [-0.68656719  0.88557214]
  [-0.10

Simulating:  52%|█████▏    | 26/50 [01:22<01:07,  2.82s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.716, -0.766)
  J1: (-0.896, -0.826)
  J2: (-0.726, 0.318)
  J3: (0.776, 0.458)
  J4: (0.607, -0.080)
[[[-0.71641791 -0.76616913]
  [-0.89552242 -0.82587063]
  [-0.72636819  0.31840795]
  [ 0.77611941  0.45771143]
  [ 0.60696518 -0.07960199]]

 [[-0.71641791 -0.76616913]
  [-0.8944532  -0.82898734]
  [-0.72636819  0.31840795]
  [ 0.77629985  0.45575136]
  [ 0.60751754 -0.081679  ]]

 [[-0.71641791 -0.76616913]
  [-0.89332976 -0.83208492]
  [-0.72636819  0.31840795]
  [ 0.7764684   0.45389464]
  [ 0.60808539 -0.08366096]]

 ...

 [[-0.71641791 -0.76616913]
  [-0.89840149 -0.81641521]
  [-0.72636819  0.31840795]
  [ 0.77550215  0.46421585]
  [ 0.60540029 -0.07279832]]

 [[-0.71641791 -0.76616913]
  [-0.89749686 -0.81958361]
  [-0.72636819  0.31840795]
  [ 0.77572104  0.46194327]
  [ 0.60590666 -0.07516187]]

 [[-0.71641791 -0.76616913]
  [-0.89653707 -0.82273574]
  [-0.72636819  0.31840795]
  [ 0.77592663  0.45977526]
  [ 0.60642

Simulating:  54%|█████▍    | 27/50 [01:25<01:06,  2.88s/it]


[Temp=2.0] Pred mech: Steph1T1
Pred joint positions:
  J0: (0.109, 0.647)
  J1: (0.756, -0.020)
  J2: (0.806, -0.886)
  J3: (0.169, -0.219)
  J4: (-0.816, -0.398)
  J5: (0.925, 0.418)
  J6: (0.687, -0.468)
  J7: (-0.129, 0.527)
[[[ 1.09452739e-01  6.46766186e-01]
  [-4.85956400e-01 -6.61425762e-02]
  [ 8.05970132e-01 -8.85572135e-01]
  ...
  [ 4.77446877e-01  3.81470254e-01]
  [-3.93357301e-01  9.34314154e-02]
  [ 1.11639894e-01  1.27697628e+00]]

 [[ 1.09452739e-01  6.46766186e-01]
  [-4.73423743e-01 -7.64253190e-02]
  [ 8.05970132e-01 -8.85572135e-01]
  ...
  [ 4.07706514e-01  3.61307985e-01]
  [-4.55786088e-01  5.20397913e-02]
  [ 9.05808106e-02  1.21706504e+00]]

 [[ 1.09452739e-01  6.46766186e-01]
  [-4.60713536e-01 -8.64877707e-02]
  [ 8.05970132e-01 -8.85572135e-01]
  ...
  [ 3.57156171e-01  3.44017216e-01]
  [-5.00577992e-01  1.91197037e-02]
  [ 7.17230655e-02  1.17162659e+00]]

 ...

 [[ 1.09452739e-01  6.46766186e-01]
  [ 1.03713316e+00  6.00290507e-01]
  [ 8.05970132e-01 -8

Simulating:  56%|█████▌    | 28/50 [01:29<01:09,  3.16s/it]

✅ Saved: results_coupler/sample_027_Steph1T2/temp_2.0.png

=== Sample 28 | GT=Watt1T1A1 ===
GT joint positions:
  J0: (-0.557, -0.149)
  J1: (-0.955, 0.647)
  J2: (-0.070, 0.259)
  J3: (0.806, 0.955)
  J4: (0.776, 0.368)
  J5: (-0.915, -0.627)
  J6: (-0.398, -0.667)
  J7: (0.299, 0.836)

[Temp=0.1] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (-0.557, -0.398)
  J1: (-0.866, 0.458)
  J2: (-0.856, -0.706)
  J3: (-0.995, 0.866)
  J4: (0.030, -0.577)
  J5: (0.488, 0.378)
  J6: (-0.119, 0.547)
  J7: (0.020, 0.109)
[[[-0.5572139  -0.39800996]
  [ 0.29657952 -0.71176473]
  [-0.85572141 -0.70646769]
  ...
  [-0.24528585 -0.07012871]
  [-0.11940298  0.54726368]
  [-0.21961096 -1.51118296]]

 [[-0.5572139  -0.39800996]
  [ 0.30192526 -0.69681619]
  [-0.85572141 -0.70646769]
  ...
  [-0.24687224 -0.06980313]
  [-0.11940298  0.54726368]
  [-0.11720541 -1.55112972]]

 [[-0.5572139  -0.39800996]
  [ 0.30700929 -0.68177664]
  [-0.85572141 -0.70646769]
  ...
  [-0.24838074 -0.06948959]
  [-0.11940

Simulating:  58%|█████▊    | 29/50 [01:32<01:06,  3.17s/it]

✅ Saved: results_coupler/sample_028_Watt1T1A1/temp_2.0.png

=== Sample 29 | GT=RRRR ===
GT joint positions:
  J0: (-0.458, 0.468)
  J1: (-0.139, 0.179)
  J2: (0.507, 0.189)
  J3: (0.796, 0.149)
  J4: (0.856, -0.149)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (-0.458, 0.468)
  J1: (-0.139, 0.179)
  J2: (0.507, 0.189)
  J3: (0.796, 0.149)
  J4: (0.856, -0.149)
[[[-0.45771143  0.46766168]
  [-0.7174195   0.12531595]
  [ 0.50746268  0.18905473]
  [ 0.21779716  0.15834188]
  [ 0.29740942 -0.13548265]]

 [[-0.45771143  0.46766168]
  [-0.71140519  0.12083556]
  [ 0.50746268  0.18905473]
  [ 0.22439429  0.12034024]
  [ 0.29343048 -0.17614749]]

 [[-0.45771143  0.46766168]
  [-0.7053136   0.11646081]
  [ 0.50746268  0.18905473]
  [ 0.23032959  0.09935163]
  [ 0.29409113 -0.19831502]]

 [[-0.45771143  0.46766168]
  [-0.69914659  0.11219305]
  [ 0.50746268  0.18905473]
  [ 0.23619524  0.08292571]
  [ 0.29608292 -0.21554445]]

 [[-0.45771143  0.46766168]
  [-0.69290603  0.10803356]
  

Simulating:  60%|██████    | 30/50 [01:34<00:58,  2.93s/it]


[Temp=2.0] Pred mech: Steph3T1A1
Pred joint positions:
  J0: (-0.458, 0.468)
  J1: (-0.139, 0.179)
  J2: (0.507, 0.189)
  J3: (0.796, -0.408)
  J4: (0.149, 0.856)
  J5: (-0.149, 0.796)
  J6: (-0.338, 0.736)
[[[-0.45771143  0.46766168]
  [-0.4665939   0.03804559]
  [ 0.50746268  0.18905473]
  [ 0.51180255 -0.4740239 ]
  [-0.23187107  0.73516892]
  [-0.53555497  0.75631265]
  [-0.33830845  0.73631841]]

 [[-0.45771143  0.46766168]
  [-0.45909471  0.037956  ]
  [ 0.50746268  0.18905473]
  [ 0.51939739 -0.47393069]
  [-0.22450213  0.73512317]
  [-0.5149081   0.82642127]
  [-0.33830845  0.73631841]]

 [[-0.45771143  0.46766168]
  [-0.4515951   0.03799731]
  [ 0.50746268  0.18905473]
  [ 0.52696932 -0.47375112]
  [-0.21710103  0.73519761]
  [-0.49673661  0.85550934]
  [-0.33830845  0.73631841]]

 [[-0.45771143  0.46766168]
  [-0.44409736  0.03816949]
  [ 0.50746268  0.18905473]
  [ 0.53451565 -0.47348602]
  [-0.20966949  0.73539206]
  [-0.48041172  0.87456681]
  [-0.33830845  0.73631841]]



Simulating:  62%|██████▏   | 31/50 [01:37<00:57,  3.00s/it]


[Temp=2.0] Pred mech: Watt1T3A1
Pred joint positions:
  J0: (0.378, 0.249)
  J1: (0.507, -0.876)
  J2: (0.030, 0.637)
  J3: (0.856, -0.408)
  J4: (-0.418, -0.229)
  J5: (-0.070, -0.318)
  J6: (0.378, 0.935)
[[[ 0.37810946  0.24875621]
  [-0.71794401  0.53093566]
  [ 0.02985075  0.63681591]
  ...
  [-0.30901616 -0.52139507]
  [-0.79140875  1.13469762]
  [-1.58966635  0.06927888]]

 [[ 0.37810946  0.24875621]
  [-0.72270179  0.51176391]
  [ 0.02985075  0.63681591]
  ...
  [-0.19332807 -0.48542485]
  [-0.82151622  1.08125673]
  [-1.53280002 -0.04409106]]

 [[ 0.37810946  0.24875621]
  [-0.72712424  0.49251205]
  [ 0.02985075  0.63681591]
  ...
  [-0.10612222 -0.45034449]
  [-0.84398026  1.03527887]
  [-1.48048777 -0.13399034]]

 ...

 [[ 0.37810946  0.24875621]
  [ 0.24875623  1.37313434]
  [ 0.02985075  0.63681591]
  ...
  [-0.87621406  1.27793026]
  [ 0.79029307  1.22339994]
  [ 0.0575108   2.33486853]]

 [[ 0.37810946  0.24875621]
  [ 0.22915283  1.37070557]
  [ 0.02985075  0.63681591

Simulating:  64%|██████▍   | 32/50 [01:41<00:55,  3.10s/it]


[Temp=2.0] Pred mech: Watt1T2A2
Pred joint positions:
  J0: (0.428, 0.627)
  J1: (0.896, -0.368)
  J2: (-0.109, 0.806)
  J3: (0.408, -0.090)
  J4: (-0.935, -0.080)
  J5: (0.219, -0.348)
  J6: (0.239, -0.507)
  J7: (0.766, 0.557)
[[[ 4.27860707e-01  6.26865685e-01]
  [ 9.12814857e-02 -4.19793970e-01]
  [-1.09452739e-01  8.05970132e-01]
  [-4.17174378e-01 -1.81442581e-01]
  [-1.75687960e+00 -2.79929382e-01]
  [-3.89992707e-01  5.62119766e-02]
  [-5.37316434e-01 -7.33056678e-03]
  [ 6.32237761e-01 -2.16593845e-01]]

 [[ 4.27860707e-01  6.26865685e-01]
  [ 1.09599478e-01 -4.25508676e-01]
  [-1.09452739e-01  8.05970132e-01]
  [-3.98777429e-01 -1.86988929e-01]
  [-1.73851519e+00 -2.85032091e-01]
  [-3.79908863e-01  4.20253798e-02]
  [-5.11091823e-01 -5.03486782e-02]
  [ 6.76527722e-01 -1.55930789e-02]]

 [[ 4.27860707e-01  6.26865685e-01]
  [ 1.28014416e-01 -4.30902818e-01]
  [-1.09452739e-01  8.05970132e-01]
  [-3.80273912e-01 -1.92194366e-01]
  [-1.72004798e+00 -2.89740178e-01]
  [-3.6957

Simulating:  66%|██████▌   | 33/50 [01:43<00:49,  2.90s/it]

✅ Saved: results_coupler/sample_032_RRRR/temp_2.0.png

=== Sample 33 | GT=Watt1T3A2 ===
GT joint positions:
  J0: (0.259, 0.139)
  J1: (0.169, 0.786)
  J2: (0.587, -0.766)
  J3: (-0.667, 0.060)
  J4: (0.985, -0.537)
  J5: (0.687, 0.418)
  J6: (-0.239, -0.159)

[Temp=0.1] Pred mech: Watt1T3A2
Pred joint positions:
  J0: (0.259, 0.139)
  J1: (0.169, 0.786)
  J2: (0.587, -0.766)
  J3: (-0.667, 0.060)
  J4: (0.985, -0.537)
  J5: (0.687, 0.418)
  J6: (-0.239, -0.159)
[[[ 0.25870648  0.13930348]
  [ 0.65964408 -0.37603632]
  [ 0.58706468 -0.76616913]
  ...
  [-0.86194935 -0.05694017]
  [ 0.02747173 -0.3159076 ]
  [ 0.11536859  0.77112997]]

 [[ 0.25870648  0.13930348]
  [ 0.66857694 -0.3689605 ]
  [ 0.58706468 -0.76616913]
  ...
  [-0.88033285 -0.23499266]
  [ 0.03545148 -0.31987387]
  [-0.07935727  0.76465159]]

 [[ 0.25870648  0.13930348]
  [ 0.67738494 -0.36172987]
  [ 0.58706468 -0.76616913]
  ...
  [-0.87716387 -0.3405897 ]
  [ 0.04349923 -0.32370028]
  [-0.19133498  0.74130181]]

 ...


Simulating:  68%|██████▊   | 34/50 [01:47<00:50,  3.15s/it]

✅ Saved: results_coupler/sample_033_Watt1T3A2/temp_2.0.png

=== Sample 34 | GT=Watt1T3A2 ===
GT joint positions:
  J0: (0.826, 0.438)
  J1: (-0.229, -0.408)
  J2: (-0.139, -0.886)
  J3: (-0.557, 0.886)
  J4: (-0.637, -0.517)
  J5: (0.458, 0.537)
  J6: (0.577, -0.159)

[Temp=0.1] Pred mech: Watt1T3A2
Pred joint positions:
  J0: (0.826, 0.438)
  J1: (-0.229, -0.408)
  J2: (-0.139, -0.886)
  J3: (-0.557, 0.886)
  J4: (-0.637, -0.517)
  J5: (0.458, 0.537)
  J6: (0.577, -0.159)
[[[ 0.82587063  0.43781096]
  [ 0.35739805 -0.83038066]
  [-0.13930348 -0.88557214]
  ...
  [ 0.1900633  -0.44255272]
  [ 0.45904902  0.33348524]
  [ 1.16504554  0.36450991]]

 [[ 0.82587063  0.43781096]
  [ 0.3796024  -0.83836348]
  [-0.13930348 -0.88557214]
  ...
  [ 0.16138184 -0.4767128 ]
  [ 0.46092563  0.32709921]
  [ 1.1667402   0.29217929]]

 [[ 0.82587063  0.43781096]
  [ 0.40194268 -0.84595756]
  [-0.13930348 -0.88557214]
  ...
  [ 0.1513681  -0.50592256]
  [ 0.4629134   0.3207469 ]
  [ 1.16609714  0.250559

Simulating:  70%|███████   | 35/50 [01:50<00:47,  3.18s/it]

✅ Saved: results_coupler/sample_034_Watt1T3A2/temp_2.0.png

=== Sample 35 | GT=Steph3T2A1 ===
GT joint positions:
  J0: (-0.915, -0.438)
  J1: (0.100, -0.458)
  J2: (-0.597, -0.945)
  J3: (-0.607, 0.716)
  J4: (0.677, 0.945)
  J5: (-0.438, 0.239)
  J6: (0.816, -0.478)
  J7: (0.846, 0.050)

[Temp=0.1] Pred mech: Steph3T2A1
Pred joint positions:
  J0: (-0.915, -0.438)
  J1: (0.100, -0.458)
  J2: (-0.597, -0.945)
  J3: (-0.607, 0.716)
  J4: (0.677, 0.945)
  J5: (-0.438, 0.239)
  J6: (0.816, -0.478)
  J7: (0.846, 0.050)
[[[-0.91542286 -0.43781096]
  [-0.58699827 -1.39833518]
  [-0.5970149  -0.94527364]
  ...
  [ 0.28070643 -1.81874687]
  [ 0.81592041 -0.47761193]
  [-0.9721968  -2.15573079]]

 [[-0.91542286 -0.43781096]
  [-0.57028483 -1.39245709]
  [-0.5970149  -0.94527364]
  ...
  [ 0.40989118 -1.86333817]
  [ 0.81592041 -0.47761193]
  [-0.86339975 -2.11244637]]

 [[-0.91542286 -0.43781096]
  [-0.55367653 -1.3862882 ]
  [-0.5970149  -0.94527364]
  ...
  [ 0.5113907  -1.88912126]
  [ 0.81

Simulating:  72%|███████▏  | 36/50 [01:54<00:45,  3.24s/it]

✅ Saved: results_coupler/sample_035_Steph3T2A1/temp_2.0.png

=== Sample 36 | GT=RRRR ===
GT joint positions:
  J0: (-0.607, 0.209)
  J1: (0.886, -0.428)
  J2: (-0.756, 0.587)
  J3: (0.766, 0.458)
  J4: (0.587, 0.398)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (-0.607, 0.209)
  J1: (0.886, -0.428)
  J2: (-0.756, 0.587)
  J3: (0.766, 0.458)
  J4: (0.587, 0.398)
[[[-0.60696518  0.20895523]
  [ 0.88557214 -0.42786071]
  [-0.75621891  0.58706468]
  [ 0.76616913  0.45771143]
  [ 0.58706468  0.39800996]]

 [[-0.60696518  0.20895523]
  [ 0.89645879 -0.40171535]
  [-0.75621891  0.58706468]
  [ 0.76807921  0.48260008]
  [ 0.58958955  0.42108495]]

 [[-0.60696518  0.20895523]
  [ 0.90688748 -0.37538397]
  [-0.75621891  0.58706468]
  [ 0.76958626  0.50759024]
  [ 0.59172677  0.44427619]]

 ...

 [[-0.60696518  0.20895523]
  [ 0.85019829 -0.50510134]
  [-0.75621891  0.58706468]
  [ 0.75806283  0.38372156]
  [ 0.57720849  0.32955165]]

 [[-0.60696518  0.20895523]
  [ 0.86243837 -0.47956

Simulating:  74%|███████▍  | 37/50 [01:56<00:39,  3.03s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.607, 0.209)
  J1: (0.458, 0.587)
  J2: (0.129, 0.269)
  J3: (0.876, 0.000)
  J4: (0.915, 0.886)
[[[-0.60696518  0.20895523]
  [-0.83121112 -0.89839152]
  [ 0.12935324  0.26865673]
  [-0.40587502 -0.31668427]
  [-1.25881834 -0.55815849]]

 [[-0.60696518  0.20895523]
  [-0.8118511  -0.90213649]
  [ 0.12935324  0.26865673]
  [-0.43685336 -0.28677415]
  [-1.26651269 -0.59900404]]

 [[-0.60696518  0.20895523]
  [-0.79242867 -0.90554302]
  [ 0.12935324  0.26865673]
  [-0.45291317 -0.26991471]
  [-1.26354118 -0.62866859]]

 ...

 [[-0.60696518  0.20895523]
  [-0.96643588  1.28006861]
  [ 0.12935324  0.26865673]
  [-0.35739236  0.89489318]
  [-0.65578723  1.72962824]]

 [[-0.60696518  0.20895523]
  [-0.98507464  1.27363184]
  [ 0.12935324  0.26865673]
  [-0.38848208  0.86943952]
  [-0.66040195  1.71317034]]

 [[-0.60696518  0.20895523]
  [-1.00359822  1.26687077]
  [ 0.12935324  0.26865673]
  [-0.42899125  0.83199038]
  [-0.65635305  

Simulating:  76%|███████▌  | 38/50 [01:59<00:37,  3.12s/it]


[Temp=2.0] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (-0.945, -0.965)
  J1: (-0.975, 0.249)
  J2: (-0.706, 0.577)
  J3: (0.836, -0.219)
  J4: (0.020, -0.408)
  J5: (0.756, 0.806)
  J6: (-0.338, -0.577)
  J7: (0.945, -0.746)
[[[-0.94527364 -0.96517414]
  [-0.97512436  0.24875621]
  [-0.70646769  0.5771144 ]
  ...
  [ 0.75621891  0.80597013]
  [-0.33830845 -0.5771144 ]
  [ 0.94527364 -0.74626863]]

 [[-0.94527364 -0.96517414]
  [-0.99630582  0.24805036]
  [-0.70646769  0.5771144 ]
  ...
  [ 0.69419039  0.8528713 ]
  [-0.33830845 -0.5771144 ]
  [ 0.87940671 -0.82884583]]

 [[-0.94527364 -0.96517414]
  [-1.01747173  0.24697495]
  [-0.70646769  0.5771144 ]
  ...
  [ 0.62640772  0.89944771]
  [-0.33830845 -0.5771144 ]
  [ 0.81387572 -0.90375066]]

 ...

 [[-0.94527364 -0.96517414]
  [-0.91155124  0.24865483]
  [-0.70646769  0.5771144 ]
  ...
  [ 0.9108825   0.66805022]
  [-0.33830845 -0.5771144 ]
  [ 1.13530526 -0.45018805]]

 [[-0.94527364 -0.96517414]
  [-0.93274062  0.2490585 ]
  

Simulating:  78%|███████▊  | 39/50 [02:03<00:34,  3.17s/it]


[Temp=2.0] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (0.985, -0.010)
  J1: (0.080, -0.766)
  J2: (0.935, -0.408)
  J3: (0.985, -0.806)
  J4: (0.259, 0.239)
  J5: (-0.378, -0.090)
  J6: (-0.408, -0.826)
  J7: (0.060, -0.050)
[[[ 0.98507464 -0.00995025]
  [-0.07644751 -0.52465254]
  [ 0.93532336 -0.40796021]
  ...
  [-0.1047951  -0.15419603]
  [-0.40796021 -0.82587063]
  [ 0.07788835  0.17522678]]

 [[ 0.98507464 -0.00995025]
  [-0.06730304 -0.54310026]
  [ 0.93532336 -0.40796021]
  ...
  [-0.1453708  -0.13731951]
  [-0.40796021 -0.82587063]
  [ 0.07599532  0.15912207]]

 [[ 0.98507464 -0.00995025]
  [-0.05783801 -0.56138558]
  [ 0.93532336 -0.40796021]
  ...
  [-0.17620458 -0.12633852]
  [-0.40796021 -0.82587063]
  [ 0.07420079  0.14304069]]

 ...

 [[ 0.98507464 -0.00995025]
  [ 2.01555816 -0.58427718]
  [ 0.93532336 -0.40796021]
  ...
  [ 0.30788642 -0.65088647]
  [-0.40796021 -0.82587063]
  [ 1.70534332 -1.23035563]]

 [[ 0.98507464 -0.00995025]
  [ 2.0254246  -0.56620529]
  

Simulating:  80%|████████  | 40/50 [02:05<00:29,  2.94s/it]


[Temp=2.0] Pred mech: UNKNOWN
Pred joint positions:
  J0: (0.647, -0.458)
  J1: (0.328, -0.169)
  J2: (0.398, -0.677)
  J3: (-0.239, 0.318)
  J4: (0.647, -0.259)
  J5: (-0.328, -0.149)
  J6: (0.647, -0.418)
  J7: (0.000, 0.328)
None

=== Sample 40 | GT=RRRR ===
GT joint positions:
  J0: (0.488, -0.139)
  J1: (-0.398, -0.010)
  J2: (-0.607, 0.249)
  J3: (-0.886, 0.577)
  J4: (0.617, -0.806)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (0.488, -0.139)
  J1: (-0.398, -0.010)
  J2: (-0.607, 0.249)
  J3: (-0.886, 0.577)
  J4: (0.617, -0.806)
[[[ 0.48756218 -0.13930348]
  [-0.39800996 -0.00995025]
  [-0.60696518  0.24875621]
  [-0.88557214  0.5771144 ]
  [ 0.6169154  -0.80597013]]

 [[ 0.48756218 -0.13930348]
  [-0.4001326  -0.02542531]
  [-0.60696518  0.24875621]
  [-0.96585325  0.48674842]
  [ 0.71721078 -0.66983582]]

 [[ 0.48756218 -0.13930348]
  [-0.40198485 -0.04093507]
  [-0.60696518  0.24875621]
  [-0.9900856   0.44537686]
  [ 0.74310961 -0.63463518]]

 [[ 0.48756218 -0.1

Simulating:  82%|████████▏ | 41/50 [02:08<00:25,  2.80s/it]

✅ Saved: results_coupler/sample_040_RRRR/temp_2.0.png

=== Sample 41 | GT=Steph3T1A2 ===
GT joint positions:
  J0: (0.488, 0.587)
  J1: (0.746, 0.279)
  J2: (0.726, -0.448)
  J3: (-0.836, 0.498)
  J4: (0.100, 0.886)
  J5: (-0.736, -0.179)
  J6: (-0.020, -0.975)

[Temp=0.1] Pred mech: Steph3T1A2
Pred joint positions:
  J0: (0.488, 0.587)
  J1: (0.746, 0.279)
  J2: (0.726, -0.448)
  J3: (-0.836, 0.498)
  J4: (0.100, 0.886)
  J5: (-0.736, -0.179)
  J6: (-0.020, -0.975)
[[[ 0.48756218  0.58706468]
  [ 0.74626863  0.27860695]
  [ 0.72636819 -0.44776121]
  ...
  [ 0.09950249  0.88557214]
  [-0.73631841 -0.17910448]
  [-0.0199005  -0.97512436]]

 [[ 0.48756218  0.58706468]
  [ 0.75161256  0.28316898]
  [ 0.72636819 -0.44776121]
  ...
  [ 0.09930514  0.88417499]
  [-0.73723869 -0.17993369]
  [-0.0199005  -0.97512436]]

 [[ 0.48756218  0.58706468]
  [ 0.75687605  0.28782358]
  [ 0.72636819 -0.44776121]
  ...
  [ 0.09911775  0.88285903]
  [-0.73810472 -0.18071578]
  [-0.0199005  -0.97512436]]

 

Simulating:  84%|████████▍ | 42/50 [02:11<00:23,  2.95s/it]


[Temp=2.0] Pred mech: Steph3T1A2
Pred joint positions:
  J0: (0.488, 0.498)
  J1: (0.886, 0.726)
  J2: (0.279, 0.279)
  J3: (0.746, -0.109)
  J4: (-0.179, -0.299)
  J5: (-0.866, -0.109)
  J6: (-0.935, -0.338)
[[[ 0.48756218  0.49751243]
  [ 0.81725887  0.1780019 ]
  [ 0.27860695  0.27860695]
  ...
  [-0.48040629 -0.5290847 ]
  [-1.17314996 -0.36409266]
  [-0.93532336 -0.33830845]]

 [[ 0.48756218  0.49751243]
  [ 0.82278488  0.18380456]
  [ 0.27860695  0.27860695]
  ...
  [-0.48592819 -0.5026183 ]
  [-1.17366997 -0.31788217]
  [-0.93532336 -0.33830845]]

 [[ 0.48756218  0.49751243]
  [ 0.82820878  0.18970279]
  [ 0.27860695  0.27860695]
  ...
  [-0.48524734 -0.48760023]
  [-1.17010697 -0.29245045]
  [-0.93532336 -0.33830845]]

 ...

 [[ 0.48756218  0.49751243]
  [ 0.13638069  0.79324617]
  [ 0.27860695  0.27860695]
  ...
  [-0.46398274 -0.55711308]
  [-1.16183096 -0.41525395]
  [-0.93532336 -0.33830845]]

 [[ 0.48756218  0.49751243]
  [ 0.13127291  0.78707217]
  [ 0.27860695  0.278606

Simulating:  86%|████████▌ | 43/50 [02:15<00:23,  3.31s/it]

✅ Saved: results_coupler/sample_042_Watt2T2A1/temp_2.0.png

=== Sample 43 | GT=RRRR ===
GT joint positions:
  J0: (-0.348, -0.726)
  J1: (0.249, -0.836)
  J2: (0.090, -0.139)
  J3: (-0.975, -0.876)
  J4: (-0.249, 0.159)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (-0.348, -0.726)
  J1: (0.249, -0.836)
  J2: (0.090, -0.139)
  J3: (-0.975, -0.876)
  J4: (-0.249, 0.159)
[[[-0.3482587  -0.72636819]
  [ 0.24875621 -0.83582091]
  [ 0.08955224 -0.13930348]
  [-0.97512436 -0.87562191]
  [-0.24875621  0.15920398]]

 [[-0.3482587  -0.72636819]
  [ 0.2505755  -0.8253849 ]
  [ 0.08955224 -0.13930348]
  [-0.9727776  -0.8790037 ]
  [-0.25814126  0.16395853]]

 [[-0.3482587  -0.72636819]
  [ 0.25221237 -0.81491872]
  [ 0.08955224 -0.13930348]
  [-0.97045865 -0.882323  ]
  [-0.26762334  0.16862792]]

 ...

 [[-0.3482587  -0.72636819]
  [ 0.24220971 -0.86691626]
  [ 0.08955224 -0.13930348]
  [-0.98231653 -0.86511229]
  [-0.22120899  0.14443742]]

 [[-0.3482587  -0.72636819]
  [ 0.24457268 -

Simulating:  88%|████████▊ | 44/50 [02:18<00:18,  3.15s/it]

✅ Saved: results_coupler/sample_043_RRRR/temp_2.0.png

=== Sample 44 | GT=Watt2T1A1 ===
GT joint positions:
  J0: (0.468, 0.269)
  J1: (-0.488, 0.209)
  J2: (0.020, 0.239)
  J3: (-0.199, -0.308)
  J4: (0.776, -0.438)
  J5: (-0.109, -0.786)
  J6: (0.040, 0.547)
  J7: (0.338, -0.786)

[Temp=0.1] Pred mech: Watt2T1A2
Pred joint positions:
  J0: (0.468, 0.269)
  J1: (-0.488, 0.209)
  J2: (0.020, 0.239)
  J3: (-0.199, -0.308)
  J4: (0.776, -0.438)
  J5: (-0.109, -0.786)
  J6: (0.040, 0.547)
  J7: (0.338, -0.786)
[[[ 0.46766168  0.26865673]
  [ 0.70606258  1.19557738]
  [ 0.0199005   0.23880596]
  ...
  [-1.25106087  0.1815725 ]
  [ 0.03980099  0.54726368]
  [ 0.05800161  0.07658062]]

 [[ 0.46766168  0.26865673]
  [ 0.68984928  1.19959688]
  [ 0.0199005   0.23880596]
  ...
  [-1.2497042   0.17681698]
  [ 0.03980099  0.54726368]
  [ 0.00486285  0.10281506]]

 [[ 0.46766168  0.26865673]
  [ 0.67356829  1.2033328 ]
  [ 0.0199005   0.23880596]
  ...
  [-1.24804113  0.17107613]
  [ 0.03980099  0

Simulating:  90%|█████████ | 45/50 [02:21<00:15,  3.19s/it]

✅ Saved: results_coupler/sample_044_Watt2T1A1/temp_2.0.png

=== Sample 45 | GT=Steph1T2 ===
GT joint positions:
  J0: (0.945, -0.886)
  J1: (0.100, 0.836)
  J2: (-0.398, 0.010)
  J3: (-0.716, -0.507)
  J4: (-0.299, 0.418)
  J5: (0.687, 0.507)
  J6: (0.070, -0.985)
  J7: (0.617, -0.209)

[Temp=0.1] Pred mech: Steph1T2
Pred joint positions:
  J0: (0.945, -0.886)
  J1: (0.100, 0.836)
  J2: (-0.398, 0.010)
  J3: (-0.716, -0.507)
  J4: (-0.299, 0.418)
  J5: (0.687, 0.507)
  J6: (0.070, -0.985)
  J7: (0.617, -0.209)
[[[ 9.45273638e-01 -8.85572135e-01]
  [ 1.56443182e+00  9.29687077e-01]
  [-3.98009956e-01  9.95024852e-03]
  [ 1.87569313e-01  1.71804142e-01]
  [ 9.87488975e-01  9.15615287e-01]
  [-1.53090383e+00  3.84620338e-01]
  [-3.47263576e-01  1.48336875e+00]
  [-1.16854852e+00  1.00655653e+00]]

 [[ 9.45273638e-01 -8.85572135e-01]
  [ 1.53265688e+00  9.40216405e-01]
  [-3.98009956e-01  9.95024852e-03]
  [ 2.02297503e-01  1.03388561e-01]
  [ 9.56047490e-01  9.16077717e-01]
  [-1.48030045

Simulating:  92%|█████████▏| 46/50 [02:24<00:12,  3.21s/it]

✅ Saved: results_coupler/sample_045_Steph1T2/temp_2.0.png

=== Sample 46 | GT=Watt1T2A2 ===
GT joint positions:
  J0: (0.179, -0.547)
  J1: (-0.338, -0.856)
  J2: (-0.756, 0.358)
  J3: (0.786, -0.299)
  J4: (-0.209, 0.308)
  J5: (-0.149, -0.179)
  J6: (0.846, -0.995)
  J7: (0.199, 0.637)

[Temp=0.1] Pred mech: Watt1T2A2
Pred joint positions:
  J0: (0.179, -0.547)
  J1: (-0.338, -0.856)
  J2: (-0.756, 0.358)
  J3: (0.786, -0.299)
  J4: (-0.209, 0.308)
  J5: (-0.149, -0.179)
  J6: (0.846, -0.995)
  J7: (0.199, 0.637)
[[[ 0.17910448 -0.54726368]
  [-0.33830845 -0.85572141]
  [-0.75621891  0.35820895]
  ...
  [-0.14925373 -0.17910448]
  [ 0.84577113 -0.99502486]
  [ 0.19900498  0.63681591]]

 [[ 0.17910448 -0.54726368]
  [-0.33284632 -0.86470454]
  [-0.75621891  0.35820895]
  ...
  [-0.15562898 -0.18489119]
  [ 0.83138029 -1.01048991]
  [ 0.20058126  0.62758925]]

 [[ 0.17910448 -0.54726368]
  [-0.32722824 -0.87359096]
  [-0.75621891  0.35820895]
  ...
  [-0.16190227 -0.19078829]
  [ 0.817

Simulating:  94%|█████████▍| 47/50 [02:28<00:09,  3.27s/it]

✅ Saved: results_coupler/sample_046_Watt1T2A2/temp_2.0.png

=== Sample 47 | GT=RRRR ===
GT joint positions:
  J0: (0.119, 0.448)
  J1: (0.139, -0.776)
  J2: (0.338, -0.299)
  J3: (-0.995, -0.308)
  J4: (0.498, -0.408)

[Temp=0.1] Pred mech: RRRR
Pred joint positions:
  J0: (0.119, 0.448)
  J1: (0.139, -0.776)
  J2: (0.338, -0.299)
  J3: (-0.995, -0.308)
  J4: (0.498, -0.408)
[[[ 0.11940298  0.44776121]
  [ 0.13930348 -0.77611941]
  [ 0.33830845 -0.29850745]
  [-0.99502486 -0.3084577 ]
  [ 0.49751243 -0.40796021]]

 [[ 0.11940298  0.44776121]
  [ 0.16066011 -0.7755857 ]
  [ 0.33830845 -0.29850745]
  [-0.99365705 -0.35970091]
  [ 0.50185308 -0.39160365]]

 [[ 0.11940298  0.44776121]
  [ 0.18200417 -0.77467934]
  [ 0.33830845 -0.29850745]
  [-0.9902005  -0.41226459]
  [ 0.50519622 -0.37542785]]

 ...

 [[ 0.11940298  0.44776121]
  [ 0.07522324 -0.77548364]
  [ 0.33830845 -0.29850745]
  [-0.98820992 -0.16350475]
  [ 0.47849944 -0.45732776]]

 [[ 0.11940298  0.44776121]
  [ 0.09657854 -0.77

Simulating:  96%|█████████▌| 48/50 [02:30<00:06,  3.05s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (0.119, 0.448)
  J1: (0.139, -0.776)
  J2: (0.338, -0.299)
  J3: (-0.995, -0.308)
  J4: (0.498, -0.408)
[[[ 0.11940298  0.44776121]
  [ 0.13930348 -0.77611941]
  [ 0.33830845 -0.29850745]
  [-0.99502486 -0.3084577 ]
  [ 0.49751243 -0.40796021]]

 [[ 0.11940298  0.44776121]
  [ 0.16066011 -0.7755857 ]
  [ 0.33830845 -0.29850745]
  [-0.99365705 -0.35970091]
  [ 0.50185308 -0.39160365]]

 [[ 0.11940298  0.44776121]
  [ 0.18200417 -0.77467934]
  [ 0.33830845 -0.29850745]
  [-0.9902005  -0.41226459]
  [ 0.50519622 -0.37542785]]

 ...

 [[ 0.11940298  0.44776121]
  [ 0.07522324 -0.77548364]
  [ 0.33830845 -0.29850745]
  [-0.98820992 -0.16350475]
  [ 0.47849944 -0.45732776]]

 [[ 0.11940298  0.44776121]
  [ 0.09657854 -0.77606837]
  [ 0.33830845 -0.29850745]
  [-0.9921409  -0.21029613]
  [ 0.48582782 -0.440897  ]]

 [[ 0.11940298  0.44776121]
  [ 0.11794078 -0.77628032]
  [ 0.33830845 -0.29850745]
  [-0.99446559 -0.25863148]
  [ 0.492169

Simulating:  98%|█████████▊| 49/50 [02:33<00:02,  2.92s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (0.169, -0.159)
  J1: (0.478, 0.259)
  J2: (-0.498, 0.259)
  J3: (-0.189, 0.687)
  J4: (0.706, 0.060)
[[[ 0.16915423 -0.15920398]
  [ 0.47761193  0.25870648]
  [-0.49751243  0.25870648]
  [-0.18905473  0.68656719]
  [ 0.70646769  0.05970149]]

 [[ 0.16915423 -0.15920398]
  [ 0.47027141  0.26402616]
  [-0.49751243  0.25870648]
  [-0.19644948  0.69180236]
  [ 0.69915239  0.06505018]]

 [[ 0.16915423 -0.15920398]
  [ 0.46283916  0.26921692]
  [-0.49751243  0.25870648]
  [-0.20393457  0.69691075]
  [ 0.69174472  0.07026922]]

 ...

 [[ 0.16915423 -0.15920398]
  [ 0.49906094  0.24199032]
  [-0.49751243  0.25870648]
  [-0.16743434  0.67011794]
  [ 0.727837    0.04289371]]

 [[ 0.16915423 -0.15920398]
  [ 0.49200889  0.24768688]
  [-0.49751243  0.25870648]
  [-0.174545    0.67572324]
  [ 0.7208122   0.0486216 ]]

 [[ 0.16915423 -0.15920398]
  [ 0.48485849  0.2532595 ]
  [-0.49751243  0.25870648]
  [-0.18175251  0.68120691]
  [ 0.71368837

Simulating: 100%|██████████| 50/50 [02:36<00:00,  3.12s/it]


[Temp=2.0] Pred mech: RRRR
Pred joint positions:
  J0: (-0.846, 0.478)
  J1: (0.746, 0.279)
  J2: (-0.985, 0.667)
  J3: (-0.965, 0.866)
  J4: (0.687, 0.448)
[[[-0.84577113  0.47761193]
  [-2.17785781 -0.41666917]
  [-0.98507464  0.66666669]
  [-0.81865408  0.77758647]
  [-2.00138067 -0.44881329]]

 [[-0.84577113  0.47761193]
  [-2.16204757 -0.43978108]
  [-0.98507464  0.66666669]
  [-0.80890036  0.76133254]
  [-1.98541014 -0.47103238]]

 [[-0.84577113  0.47761193]
  [-2.14583638 -0.46261355]
  [-0.98507464  0.66666669]
  [-0.80355704  0.75063312]
  [-1.96892477 -0.4922734 ]]

 ...

 [[-0.84577113  0.47761193]
  [ 0.43768691  1.44038348]
  [-0.98507464  0.66666669]
  [-1.18256778  0.63511579]
  [ 0.27537764  1.51675839]]

 [[-0.84577113  0.47761193]
  [ 0.42068875  1.46263627]
  [-0.98507464  0.66666669]
  [-1.17874964  0.61677686]
  [ 0.25650561  1.53489499]]

 [[-0.84577113  0.47761193]
  [ 0.40330482  1.48458902]
  [-0.98507464  0.66666669]
  [-1.17080024  0.592471  ]
  [ 0.23708535